### ISSUE TITLE
Display linkable Image on List Card View (using style)

### ISSUE THREAD

**Issue by cjcornell** [PropelVentures/GenericPlatform#54]
#### Display linkable Image on List Card View (using style)
- See Github issue #17   (where a method is suggested)
- Also See Github Issue #53    (for multiple selection options)

**Comment by yasirkhan177** [comment]
you haven't comment on this?

**Comment by cjcornell** [comment]
I tried to click on an image in the My Projects Box view ... and nothing happens.
It's always a good idea to point me to an example where I can test the fix.

**Comment by yasirkhan177** [comment]
now clicking on image is active ....

dd->list_select = projects,1;projects,2  << check dict_id = 112 >>>

to sets of parameters .. separated by semi colon ( ; ) 

first set is use as like before .. 2nd set tell gpc ,what to do when some one clicks on the image .. it work same like how we click on the edit button .. 

now if you click on edit button any record under my projects TAB .. it will redirect you to my projects tab .. because its tab_num=1 ... but if you click on image .. then it will redirect you to manage project tab .. because its tab_num =2 ..

**Comment by cjcornell** [comment]
I am still not sure how these parameters work  (I will wait for the basic documentation)
Also - see my comments for #17  about the potential conflicting parameters ....

**Comment by yasirkhan177** [comment]
ok will explain in basic documentation.

**Comment by cjcornell** [comment]
OK.
